import { db } from './firebase';
import { doc, setDoc } from 'firebase/firestore';

export async function seedVinayagarContent() {
    const taContent = [
        {
            title: "விநாயகர் அஷ்டோத்திரம் ஶத நாமாவளி",
            lines: [
                "1. ஓம் விநாயகாய நம !!!",
                "2. ஓம் விக்னராஜாய நம !!!",
                "3. ஓம் கெளரி புத்ராய நம !!!",
                "4. ஓம் கணேச்வராய நம !!!",
                "5. ஓம் ஸ்கந்தாக்ரஜாய நம !!!",
                "6. ஓம் அவ்யயாய நம !!!",
                "7. ஓம் பூதாய நம !!!",
                "8. ஓம் தக்ஷாய நம !!!",
                "9. ஓம் அத்யக்ஷாய நம !!!",
                "10. ஓம் த்விஜப்ரியாய நம !!!",
                "11. ஓம் அக்னிகர்பச்சிதே நம !!!",
                "12. ஓம் இந்த்ரஸ்ரீபிரதாய நம !!!",
                "13. ஓம் வாணீப்ரதாய நம !!!",
                "14. ஓம் சர்வசித்திப்ரதாய நம !!!",
                "15. ஓம் சர்வாத்மகாய நம !!!",
                "16. ஓம் சர்வரீப்ரியாய நம !!!",
                "17. ஓம் சர்வாத்மகாய நம !!!",
                "18. ஓம் ஸ்ருஷ்டிகர்த்ரே நம !!!",
                "19. ஓம் தேவாய நம !!!",
                "20. ஓம் அனேகார்ச்சிதாய நம !!!",
                "21. ஓம் சிவாய நம !!!",
                "22. ஓம் சுத்தாய நம !!!",
                "23. ஓம் புத்திப்ரியாய நம !!!",
                "24. ஓம் சாந்தாய நம !!!",
                "25. ஓம் பரஹ்மசாரிணே நம !!!",
                "26. ஓம் கஜானனாய நம !!!",
                "27. ஓம் த்வைமாத்ரேயாய நம !!!",
                "28. ஓம் முனிஸ்துத்யாய நம !!!",
                "29. ஓம் பக்தவிக்னவிநாசனாய நம !!!",
                "30. ஓம் ஏகதந்தாய நம !!!",
                "31. ஓம் சதுர்பாஹவே நம !!!",
                "32. ஓம் சதுராய நம !!!",
                "33. ஓம் சக்திசம்யுதாய நம !!!",
                "34. ஓம் மோதகப்ரியாய நம !!!",
                "35. ஓம் லம்போதராய நம !!!",
                "36. ஓம் சூர்ப்பகர்ணாய நம !!!",
                "37. ஓம் ஹரயே நம !!!",
                "38. ஓம் ப்ரஹ்மவிதுத்தமாய நம !!!",
                "39. ஓம் காலாய நம !!!",
                "40. ஓம் க்ரஹபதயே நம !!!",
                "41. ஓம் காமினே நம !!!",
                "42. ஓம் சோமஸூர்யாக்னி லோசனாய நம !!!",
                "43. ஓம் பாசாங்குசதராய நம !!!",
                "44. ஓம் சாண்டாய நம !!!",
                "45. ஓம் குணாதீதாய நம !!!",
                "46. ஓம் நிரஞ்ஜனாய நம !!!",
                "47. ஓம் அகல்மஷாய நம !!!",
                "48. ஓம் ஸ்வயம்சித்தாய நம !!!",
                "49. ஓம் சித்தார்ச்சித பதாம்புஜாய நம !!!",
                "50. ஓம் பீஜாபூர பலாஸக்தாய நம !!!",
                "51. ஓம் வரதாய நம !!!",
                "52. ஓம் சாஸ்வதாய நம !!!",
                "53. ஓம் க்ருதினே நம !!!",
                "54. ஓம் த்விஜப்ரியாய நம !!!",
                "55. ஓம் வீதபயாய நம !!!",
                "56. ஓம் கதினே நம !!!",
                "57. ஓம் சக்ரினே நம !!!",
                "58. ஓம் இக்ஷூசாபத்ருதே நம !!!",
                "59. ஓம் ஸ்ரீதாய நம !!!",
                "60. ஓம் அஜாய நம !!!",
                "61. ஓம் உத்பலகராய நம !!!",
                "62. ஓம் ஸ்ரீபதயே நம !!!",
                "63. ஓம் ஸ்துதிஹர்ஷிதாய நம !!!",
                "64. ஓம் குலாத்ரிபேத்ரே நம !!!",
                "65. ஓம் ஜடிலாய நம !!!",
                "66. ஓம் கலிகல்மஷநாசனாய நம !!!",
                "67. ஓம் சந்திரசூடாமணயே நம !!!",
                "68. ஓம் காந்தாய நம !!!",
                "69. ஓம் பாபஹரினே நம !!!",
                "70. ஓம் ஸமாஹிதாய நம !!!",
                "71. ஓம் ஆஸ்ரிதாய நம !!!",
                "72. ஓம் ஸ்ரீ கராய நம !!!",
                "73. ஓம் செளம்யாய நம !!!",
                "74. ஓம் பக்தவாஞ்சித தாயகாய நம !!!",
                "75. ஓம் சாந்தாய நம !!!",
                "76. ஓம் கைவல்யஸூகதாய நம !!!",
                "77. ஓம் சச்சிதானந்த விக்ரஹாய நம !!!",
                "78. ஓம் ஜ்ஞானினே நம !!!",
                "79. ஓம் தயாயுதாய நம !!!",
                "80. ஓம் தாந்தாய நம !!!",
                "81. ஓம் ப்ரஹ்மத்வேஷ விவர்ஜிதாய நம !!!",
                "82. ஓம் பிரமத்த தைத்ய பயதாய நம !!!",
                "83. ஓம் ஸ்ரீ கண்ட்டாய நம !!!",
                "84. ஓம் விபுதேச்வராய நம !!!",
                "85. ஓம் ரமார்ச்சிதாய நம !!!",
                "86. ஓம் விதயே நம !!!",
                "87. ஓம் நாகராஜ யஜ்ஞோபவீதவதே நம !!!",
                "88. ஓம் ஸ்த்தூலகண்ட்டாய நம !!!",
                "89. ஓம் ஸ்வயம்கர்த்ரே நம !!!",
                "90. ஓம் ஸாமகோஷப்ரியாய நம !!!",
                "91. ஓம் பரஸ்மை நம !!!",
                "92. ஓம் ஸ்த்தூலதுண்டாய நம !!!",
                "93. ஓம் அக்ரண்யை நம !!!",
                "94. ஓம் தீராய நம !!!",
                "95. ஓம் வாகீசாய நம !!!",
                "96. ஓம் ஸித்திதாயகாய நம !!!",
                "97. ஓம் தூர்வாபில்வப்ரியாய நம !!!",
                "98. ஓம் அவ்யக்தமூர்த்தயே நம !!!",
                "99. ஓம் அத்புதமூர்த்திமதே நம !!!",
                "100. ஓம் சைலேந்திர தநுஜோத் ஸங்க கேலநோத் ஸூகமானஸாய நம !!!",
                "101. ஓம் ஸ்வலாவண்ய சுதாஸாய ஜித மன்மதவிக்ராஹாய நம !!!",
                "102. ஓம் ஸமஸ்த ஜகதாதாராய நம !!!",
                "103. ஓம் மாயினே நம !!!",
                "104. ஓம் மூஷிக வாஹனாய நம !!!",
                "105. ஓம் ஹ்ருஷ்டாய நம !!!",
                "106. ஓம் துஷ்டாய நம !!!",
                "107. ஓம் பிரஸன்னாத்மனே நம !!!",
                "108. ஓம் ஸர்வஸித்தி பிரதாயகாய நம !!!"
            ],
            meaning: [
                "விநாயகருக்கு வணக்கம்.",
                "விக்னங்களின் அரசருக்கு வணக்கம்.",
                "கௌரியின் மகனுக்கு வணக்கம்.",
                "கணங்களின் ஆண்டவருக்கு வணக்கம்."
            ]
        }
    ];
    const enContent = [
        {
            title: "Vinayagar Ashtothram",
            lines: [
                "1. Om Vinayakaya Namah !!!",
                "2. Om Vighnarajaya Namah !!!",
                "3. Om Gauri Putraya Namah !!!",
                "4. Om Ganeshvaraya Namah !!!",
                "5. Om Skandagrajaya Namah !!!",
                "6. Om Avyayaya Namah !!!",
                "7. Om Bhutaya Namah !!!",
                "8. Om Dakshaya Namah !!!",
                "9. Om Adhyakshaya Namah !!!",
                "10. Om Dwijapriyaya Namah !!!",
                "11. Om Agnigarbhachide Namah !!!",
                "12. Om Indrashripradaya Namah !!!",
                "13. Om Vanipradaya Namah !!!",
                "14. Om Sarvasiddhipradaya Namah",
                "16. Om Sarvatmakaya Namah !!!",
                "17. Om Sarvaripriyaya Namah !!!",
                "18. Om Sarvatmakaya Namah !!!",
                "19. Om Srushtikartre Namah",
                "20. Om Devaya Namah !!!",
                "21. Om Anekarchitaya Namah !!!",
                "22. Om Shivaya Namah !!!",
                "23. Om Shuddhaya Namah !!!",
                "24. Om Buddhipriyaya Namah !!!",
                "25. Om Shantaya Namah !!!",
                "26. Om Brahmacharine Namah !!!",
                "27. Om Gajananaya Namah !!!",
                "28. Om Dvimatraya Namah !!!",
                "29. Om Munistutyaya Namah !!!",
                "30. Om Bhaktavighnavinashanaya Namah !!!",
                "31. Om Ekadantaya Namah !!!",
                "32. Om Chaturbahave Namah !!!",
                "33. Om Chaturaya Namah !!!",
                "34. Om Shaktisamyutaya Namah !!!",
                "36. Om Modakapriyaya Namah !!!",
                "37. Om Lambodaraya Namah !!!",
                "38. Om Surpakarnaya Namah !!!",
                "39. Om Haraye Namah !!!",
                "40. Om Brahmaviduttamaya Namah",
                "40. Om Kalaya Namah !!!",
                "41. Om Grahapathaye Namah !!!",
                "42. Om Kamine Namah",
                "43. Om Somasuryagni Lochanaya Namah",
                "44. Om Pashankushadharaya Namah !!!",
                "45. Om Chandaya Namah !!!",
                "46. Om Gunatithaya Namah !!!",
                "47. Om Niranjanaya Namah !!!",
                "48. Om Akalmashaya Namah !!!",
                "49. Om Svayamsiddhaya Namah !!!",
                "50. Om Siddharchita Padambujaya Namah !!!",
                "51. Om Bijapooraphalasaktaya Namah !!!",
                "52. Om Varadaya Namah !!!",
                "53. Om Shashvataya Namah !!!",
                "54. Om Krutinaya Namah !!!",
                "56. Om Dwijapriyaya Namah !!!",
                "57. Om Vitabhayaya Namah !!!",
                "58. Om Gadine Namah !!!",
                "59. Om Chakrine Namah !!!",
                "60. Om Ikshuchapadhrite Namah !!!",
                "61. Om Shridaya Namah !!!",
                "62. Om Ajaya Namah !!!",
                "63. Om Udbalakaya Namah !!!",
                "64. Om Shripataye Namah !!!",
                "65. Om Stutiharshitaya Namah !!!",
                "67. Om Kuladri Bhetre Namah !!!",
                "68. Om Jatilaya Namah !!!",
                "69. Om Kalikalmasanashanaya Namah !!!",
                "70. Om Chandrachoodamanaye Namah !!!",
                "71. Om Kantaya Namah !!!",
                "72. Om Papaharine Namah !!!",
                "73. Om Samahitaya Namah !!!",
                "74. Om Ashritaya Namah !!!",
                "75. Om Shrikaraya Namah !!!",
                "76. Om Saumyaya Namah !!!",
                "77. Om Bhaktavanchitadayakaya Namah !!!",
                "78. Om Shantaya Namah !!!",
                "79. Om Kaivalyasugataya Namah !!!",
                "80. Om Satchidananda Vigrahaya Namah !!!",
                "79. Om Jnanine Namah !!!",
                "82. Om Dayayutaya Namah !!!",
                "81. Om Tantaya Namah !!!",
                "83. Om Brahmadvesha Vivarjitaya Namah !!!",
                "84. Om Pramatha Daitya Bhayadaya Namah !!!",
                "86. Om Shrikantaya Namah !!!",
                "87. Om Vibhuteshvaraya Namah !!!",
                "88. Om Ramarchitaya Namah !!!",
                "89. Om Vidaye Namah !!!",
                "90. Om Nagaraja Yajnopavitavate Namah !!!",
                "91. Om Sthulakantaya Namah !!!",
                "92. Om Svayamkartraya Namah !!!",
                "93. Om Samagoshapriyaya Namah !!!",
                "94. Om Parasmai Namah !!!",
                "95. Om Sthulatundaya Namah !!!",
                "96. Om Agranyai Namah !!!",
                "97. Om Dhiraya Namah !!!",
                "98. Om Vakishaya Namah !!!",
                "99. Om Siddhidayakaya Namah !!!",
                "100. Om Durvabilvapraya Namah !!!",
                "101. Om Avyaktamurthaye Namah !!!",
                "102. Om Adbhutamurtimate Namah !!!",
                "103. Om Shailendra Tanujotsanga Khelanotsuka Manasaya Namah !!!",
                "104. Om Svalavanya Sudhasara Jita Manmathavigrahaya Namah !!!",
                "105. Om Samasta Jagadadharaya Namah !!!",
                "106. Om Mayine Namah !!!",
                "107. Om Mushikavahanaya Namah !!!",
                "108. Om Hrishtaya Namah !!!",
                "109. Om Tushtaya Namah !!!",
                "110. Om Prasannatmane Namah !!!",
                "111. Om Sarvasiddhipradayakaya Namah"
            ],
            meaning: [
                "Salutations to Vinayaka.",
                "Salutations to the king of obstacles.",
                "Salutations to the son of Gauri.",
                "Salutations to the lord of the Ganas."
            ]
        }
    ];
    await setDoc(doc(db, 'vinayagarAshtothram', 'content'), {
        ta: taContent,
        en: enContent
    });
    console.log('Vinayagar Ashtothram content seeded to Firestore!');
}

// To run this, import and call seedVinayagarContent() from a temporary script or dev screen.
